kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc
  namespace: nfs-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 11Gi
  storageClassName: netapp-sc
