apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: netapp-nfs
  namespace: trident
spec:
  version: 1
  backendName: netapp-nfs
  storageDriverName: ontap-nas
  managementLIF: 
  dataLIF: 
  svm: 
  spaceReserve: none
  defaults:
    snapshotReserve: "30"
    exportPolicy: 
  credentials:
    name: svm-cred
  labels:
    type: nfs
