apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: 
   namespace: 
spec:
   storageClassName: netapp-nas
   accessModes:
      - ReadWriteMany
   resources:
      requests:
         storage: 100Gi
