apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: netapp-nfs
provisioner: csi.trident.netapp.io
parameters:
  selector: "svm="
allowVolumeExpansion: true
reclaimPolicy: Delete
