apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: netapp-sc
provisioner: csi.trident.netapp.io
parameters:
  selector: "svm=prod-svm"
    #  trident.netapp.io/replication: "true"
    #  backendType: "ontap-nas"
allowVolumeExpansion: true
reclaimPolicy: Delete
